icons_format = "{icon}"

[theme]
theme = "nord-dark"
#[theme.overrides]
#idle_bg = "#123456"
#idle_fg = "#abcdef"

[icons]
icons = "awesome4"
[icons.overrides]
bat = ["|E|", "|_|", "|=|", "|F|"]
bat_charging = "|^| "

[[block]]
block = "cpu"
info_cpu = 20
warning_cpu = 50
critical_cpu = 90
interval = 1

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = " $icon root: $available.eng(w:2) "

[[block]]
block = "memory"
format = " $icon $mem_total_used_percents.eng(w:2) "
format_alt = " $icon_swap $swap_used_percents.eng(w:2) "

[[block]]
block = "net"
format = " $icon {$signal_strength $ssid $frequency|Wired} $device "

[[block]]
block = "sound"
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "battery"
device = "DisplayDevice"
driver = "upower"
format = " 🔋 $percentage {$time |} "
charging_format = " 🔌 $percentage {$time |} "
full_format = "🔋 100% "

[[block]]
block = "time"
interval = 1
format = " $timestamp.datetime(f:'%a %d/%m %R') "
